// Code generated by MockGen. DO NOT EDIT.
// Source: exporter.go
//
// Generated by this command:
//
//	mockgen -source=exporter.go -destination=./exporter_test.go -package=app
//

// Package app is a generated GoMock package.
package app

import (
	context "context"
	reflect "reflect"

	otlp "github.com/mashiike/go-otlp-helper/otlp"
	gomock "go.uber.org/mock/gomock"
)

// MockExporter is a mock of Exporter interface.
type MockExporter struct {
	ctrl     *gomock.Controller
	recorder *MockExporterMockRecorder
	isgomock struct{}
}

// MockExporterMockRecorder is the mock recorder for MockExporter.
type MockExporterMockRecorder struct {
	mock *MockExporter
}

// NewMockExporter creates a new mock instance.
func NewMockExporter(ctrl *gomock.Controller) *MockExporter {
	mock := &MockExporter{ctrl: ctrl}
	mock.recorder = &MockExporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExporter) EXPECT() *MockExporterMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockExporter) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockExporterMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockExporter)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockExporter) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockExporterMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockExporter)(nil).Stop), ctx)
}

// UploadLogs mocks base method.
func (m *MockExporter) UploadLogs(ctx context.Context, protoLogs []*otlp.ResourceLogs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadLogs", ctx, protoLogs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadLogs indicates an expected call of UploadLogs.
func (mr *MockExporterMockRecorder) UploadLogs(ctx, protoLogs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadLogs", reflect.TypeOf((*MockExporter)(nil).UploadLogs), ctx, protoLogs)
}

// UploadTraces mocks base method.
func (m *MockExporter) UploadTraces(ctx context.Context, protoSpans []*otlp.ResourceSpans) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadTraces", ctx, protoSpans)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadTraces indicates an expected call of UploadTraces.
func (mr *MockExporterMockRecorder) UploadTraces(ctx, protoSpans any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadTraces", reflect.TypeOf((*MockExporter)(nil).UploadTraces), ctx, protoSpans)
}
